# Generated by Django 5.2.11 on 2026-03-01 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField()),
                ("price", models.FloatField()),
                ("description", models.TextField()),
                ("seller", models.TextField()),
                ("color", models.TextField()),
                ("dimensions", models.TextField()),
            ],
        ),
    ]
