# Generated by Django 5.2.11 on 2026-03-07 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="state",
            field=models.CharField(
                choices=[("PU", "PUBLICADO"), ("BR", "BORRADOR"), ("PR", "PRIVADO")],
                default="BR",
                max_length=2,
            ),
        ),
    ]
