# Generated by Django 5.2.11 on 2026-03-07 18:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecommerce", "0002_productmodel_state"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productmodel",
            options={"ordering": ["-updated", "-timestamp"]},
        ),
        migrations.AddField(
            model_name="productmodel",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productmodel",
            name="updated",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
